-- 1. Приведение всех TIMESTAMP к TIMESTAMP WITH TIME ZONE (для корректной работы с java.time.Instant)

ALTER TABLE users
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC',
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE clients
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC',
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE employees
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC',
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE materials
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC',
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE products
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC',
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE product_materials
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC';

ALTER TABLE orders
ALTER COLUMN order_datetime TYPE TIMESTAMP WITH TIME ZONE USING order_datetime AT TIME ZONE 'UTC',
    ALTER COLUMN completed_at TYPE TIMESTAMP WITH TIME ZONE USING completed_at AT TIME ZONE 'UTC',
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC',
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE order_items
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC';

ALTER TABLE audit_log
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC';


-- 2. Приведение всех первичных ключей (id) и связанных внешних ключей к BIGINT

-- Таблицы с SERIAL → BIGINT
ALTER TABLE users
ALTER COLUMN id TYPE BIGINT USING id::BIGINT;

ALTER TABLE clients
ALTER COLUMN id TYPE BIGINT USING id::BIGINT,
    ALTER COLUMN user_id TYPE BIGINT USING user_id::BIGINT;

ALTER TABLE employees
ALTER COLUMN id TYPE BIGINT USING id::BIGINT,
    ALTER COLUMN user_id TYPE BIGINT USING user_id::BIGINT;

ALTER TABLE materials
ALTER COLUMN id TYPE BIGINT USING id::BIGINT;

ALTER TABLE products
ALTER COLUMN id TYPE BIGINT USING id::BIGINT;

ALTER TABLE product_materials
ALTER COLUMN id TYPE BIGINT USING id::BIGINT,
    ALTER COLUMN product_id TYPE BIGINT USING product_id::BIGINT,
    ALTER COLUMN material_id TYPE BIGINT USING material_id::BIGINT;

ALTER TABLE orders
ALTER COLUMN id TYPE BIGINT USING id::BIGINT,
    ALTER COLUMN client_id TYPE BIGINT USING client_id::BIGINT;

ALTER TABLE order_items
ALTER COLUMN id TYPE BIGINT USING id::BIGINT,
    ALTER COLUMN order_id TYPE BIGINT USING order_id::BIGINT,
    ALTER COLUMN product_id TYPE BIGINT USING product_id::BIGINT;